### ISSUE TITLE
Improve error message when resource name clashes.

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-cli#111]
Action, trigger and rule names must be unique within a namespace and package. It could be confusing to a developer that you cannot create an action with a name, if a trigger or rule already exists with them identifier. 

Here's the error message that gets returned if you try to do this....

```
error: Unable to create action 'hello': Resource by this name exists but is not in this collection. (code 5000008)
Run 'wsk --help' for usage.
```

It would be helpful if the CLI could return the resource details ("Trigger with name ... already exists") to help users understand this issue.

Alternatively, a more helpful error message ("Actions, rules and triggers share the same namespace, check for those resources with that name.").

**Comment by dubeejw** [comment]
I believe this error message actually originates from the OpenWhisk controller.

**Comment by rabbah** [comment]
It does. I’d close as duplicate of https://github.com/apache/incubator-openwhisk/issues/1684

**Comment by jthomas** [comment]
It is, closing....
