### ISSUE TITLE
If you specify --kind and --docker, --docker is silently ignored

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#122]
@sdague commented on [Thu Nov 16 2017](https://github.com/apache/incubator-openwhisk/issues/2977)

When you set an action using the wsk action update command, and specify both --kind and --docker, the --docker portion is silently ignored. Instead at least a warning should be provided to the users to ensure that they get something consistent.

This tripped me up when moving from a --kind python:3 to --docker <customimage> as I didn't remember to delete the --kind from my script, then my image wasn't used, the base python3action was used instead.

---

@csantanapr commented on [Thu Nov 16 2017](https://github.com/apache/incubator-openwhisk/issues/2977#issuecomment-345079610)

@jessealva take a look when you have a chance.

**Comment by jessealva** [comment]
So it looks like theres is very little/no validation in the Go around flag combinations.  Just looks like theres a specific order in which we set the `kind` for each action. Once the first condition is met, kind is set and we move on to other things

This looks like something that we could easily add for this particular issue, but might need more investigation is we wanted to be more complete  

@csantanapr thinking we could just error out quickly on this issue and then maybe open another issue around looking at validating all the flag combinations?

**Comment by jessealva** [comment]
Created a PR for a fix for this that will error out if you pass in both at the same time.  This should be good @sdague
