### ISSUE TITLE
remove NAMESPACE from wskprops file and wsk property subcommand

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#137]
@sjfink commented on [Mon Apr 17 2017](https://github.com/apache/incubator-openwhisk/issues/2150)

```
$ wsk property get --namespace
whisk namespace	      _
```

I propose `wsk property get --namespace` should always return the explicit name of the default namespace, and not `_` or `default`.

**Comment by rabbah** [comment]
the namespace property should be removed entirely and actually can lead to surprising failures when present.
