### ISSUE TITLE
Make this openwhisk cli able to be installed by major installation tools

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-cli#14]
Under mac, linux and other major operating systems, openwhisk cli needs to be installed by software management tools, like homebrew, apt-get, gem, etc.

**Comment by houshengbo** [comment]
@lzbj could u look at this issue?

**Comment by houshengbo** [comment]
As long as the binaries are copied to the place we specified, there should be no effect on the tests in openwhisk. I will close this issue here. The CLI in the new repo may need tests.

**Comment by lzbj** [comment]
@houshengbo , for brew, we can refer this article:
http://liam0205.me/2016/07/30/release-your-own-app-in-Homebrew/, what do you think?

For ubuntu, I'm still investigating.

**Comment by houshengbo** [comment]
@lzbj Good man. Please research in the major ways of releases in the three operating systems: mac, Ubuntu and windows.

**Comment by InTheCloudDan** [comment]
@lzbj not sure if you've seen these options before:

https://github.com/jordansissel/fpm

https://github.com/packpack/packpack

Out of the 2, fpm will probably be the most flexible for creating packages.

**Comment by Juice10** [comment]
Home-brew thread: https://github.com/apache/incubator-openwhisk-cli/issues/153

**Comment by mrutkows** [comment]
@Juice10 We need to assure that everytime wsk CLI is built as part of an Apache release, that the Travis is able to push a new version here...

**Comment by rabbah** [comment]
`wsk` available via `brew` now.
