### ISSUE TITLE
CLI HTTP Client Should Return HTTP Body to Commands

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#140]
@dubeejw commented on [Wed Mar 22 2017](https://github.com/apache/incubator-openwhisk/issues/2064)

As values returned from Whisk backend can get out of sync with the CLI, the HTTP body of a response should be returned to each command. This way the HTTP body can be directly printed. This allows fields to be added/removed from the backend responses without the CLI needing to be updated unless the modified fields are critical to the functionality of the CLI.

---

@dubeejw commented on [Wed Mar 22 2017](https://github.com/apache/incubator-openwhisk/issues/2064#issuecomment-288584430)

@csantanapr, @mdeuser, this is technical debt, and should be fixed ASAP.

---

@dubeejw commented on [Thu Mar 23 2017](https://github.com/apache/incubator-openwhisk/issues/2064#issuecomment-288746685)

All of the commands currently receive the HTTP response from each request, but the response body is not accessible as the connection has already been closed.

**Comment by rabbah** [comment]
@dubee @mdeuser is this still an issue?

**Comment by mdeuser** [comment]
The response body is available to the calling cli functions.  If the `-v` parameter was used to dump the response body, the body is restored into the response by the client code to ensure the caller has access to the full response
https://github.com/apache/incubator-openwhisk-client-go/blob/67f06bc4f26816140cc7a7b8deeb6ad2cad4b133/whisk/client.go#L523
