### ISSUE TITLE
Support for overriding APIHOST url template in wskprops or cli options

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-cli#162]
Reference: 
https://github.com/apache/incubator-openwhisk-client-js#constructor-options

Description:
I have an ow endpoint, for example `https://myserver.com/foo/bar`

I can't set this as `APIHOST` in `.wskprops` because it then appends `/api/v1/` to the URL when trying to connect, thus it will look like this: `https://myserver.com/foo/bar/api/v1/` then it appends the namespace, etc.

From [this link for the JS client constructor options](https://github.com/apache/incubator-openwhisk-client-js#constructor-options), I see that module supports an optional parameter `api` which does what I need. 

Is there a way in the CLI to support what I need (for wsk not to use the APIHOST url template)? If not, this is a feature request to either:
1. Add an API key in .wskprops
OR
2. option for wsk to skip using the APIHOST url template

**Comment by csantanapr** [comment]
@shazron the controller needs the /api/v1 path

Can you provide more input on the use case and requirement?

If you setup an edge like nginx and the CLI sends the request to `https://myserver.com/foo/bar/namespaces/_/action/myaction`

Then your nginx would need to insert `/api/v1` in the middle of the url coming in anyway, and remove anything extra. so I don't get the point.

IN->`https://myserver.com/foo/bar/namespaces/_/action/myaction`
nginx will massage the URL path
OUT to Controller -> `http://controllerhost:controllerport/api/v1/namespaces/_/action/myaction`

Not saying that it can't be done I just want to understand the specific use case. 

The tricky part this would be done in the go-client lower level with .wskprops

I think the fix will be the same for option 1, and 2
have a BASEPATH_V1 where by default if not specified will be `/api/v1`, or override with `/foo/bar` or `/`

**Comment by shazron** [comment]
Sorry for the late response. I just got clarification regarding my use case from an internal team. I won't be needing this support anymore :)
