### ISSUE TITLE
CLI: Support Semantic Versioning

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-cli#163]
@drcariel commented on [Thu Sep 21 2017](https://github.com/apache/incubator-openwhisk/issues/2794)

v.r.m semantic version format (i.e. 1.0.0) -- an essential initial component for release management and Homebrew support:

 - https://github.com/apache/incubator-openwhisk/issues/420#issuecomment-249195056 
 - https://github.com/apache/incubator-openwhisk/issues/2178
 - https://github.com/apache/incubator-openwhisk/issues/1880
 - https://github.com/apache/incubator-openwhisk/issues/1677

**Comment by shazron** [comment]
Seems to be a dupe of https://github.com/apache/incubator-openwhisk-cli/issues/163

**Comment by rabbah** [comment]
Closed as duplicate.
