### ISSUE TITLE
Add OS to User Agent Header

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-cli#165]
@drcariel commented on [Wed Sep 06 2017](https://github.com/apache/incubator-openwhisk/issues/2704)

Looking for OS information included on UserAgent header as discussed in
https://github.com/apache/incubator-openwhisk/pull/2591

**Comment by rabbah** [comment]
@drcariel is this done?

**Comment by drcariel** [comment]
I believe not - more of a nice to have? or should this be prioritized @rabbah ?

**Comment by rabbah** [comment]
This doesn’t strike me as particularly hard and would provide operational and usage insights so +1 from me.
