### ISSUE TITLE
Write the integration tests for CLI in Go

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-cli#17]
OpenWhisk CLI project needs to have its integration tests running against OpenWhisk. The current CLI tests are running inside openwhisk and they are written in scala. As a separate project, we need to have the tests written in Go, and establish the test environment in Travis. 

Travis CI supports Go project only under Linux so far. It deserves more investigations for Go project under mac and windows.

**Comment by rabbah** [comment]
> As a separate project, we need to have the tests written in Go, and establish the test environment in Travis.

define the purpose of the tests first.
if these are unit tests, it makes sense to have the tests in the same language framework as the rest of the code.

if there are integration tests, i would reconsider.

**Comment by houshengbo** [comment]
@rabbah @dubeejw @mdeuser From my perspective, it is also good for us to keep the integration tests consistent with the development language as well. This lows the bar for new contributors coming into this project, and reduces the complexity of setting up this project.  Folks won't have the confusion of why to maintain the development and test in two languages.

**Comment by mrutkows** [comment]
@houshengbo agree with the intent; however, if we have existing tests that need to be rewritten to Go, then we should treat that as a lower priority over the general separation/plugable framework goal.  Of course we should identify new tests and their purpose as @rabbah indicated above and record those each as issues of their own.  This issue sounds more like a general epic (goal) or placeholder and doubt it can carry all possible tests/code.

**Comment by rabbah** [comment]
We have started suites for such test here:
https://github.com/apache/incubator-openwhisk-cli/blob/master/commands/trigger_test.go
https://github.com/apache/incubator-openwhisk-cli/blob/master/commands/action_test.go

It should be a matter of project policy now to add tests for new functionality here and grow the suite. There are certain features that are easier to test this way.
