### ISSUE TITLE
Make it easier for user to save action code?

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-cli#179]
When using serverless frameworks or CI/CD pipelines to create openwhisk applications, developers are not in charge of packaging their applications for deployment. In the event of an application error, I've found myself needing to download the deployed action code to a local file for debugging.

**What about adding a flag to the CLI to make it easier for developers to save the action code to a file?** 

`$ wsk action get name --code` would dump the raw value of `exec.code` to the console. Developers can redirect this to a file or base64 decoder to decode the binary.

At the moment I have to string together `jq` and `tail` to achieve this, which is a bit of a pain and doesn't work on non-nix platforms.

```
$ wsk action get params  | tail -n +2 | jq -r '.exec.code'
```

**Comment by csantanapr** [comment]
This is already implemented.
```
👻  $ bx wsk action get -h
get action
Usage:
  wsk action get ACTION_NAME [FIELD_FILTER | --summary | --url] [flags]

Flags:
      --save             save action code to file corresponding with action name
      --save-as string   file to save action code to
```
Use `--save` or `--save-as`
For example
```
wsk action get foo --save-as foo.js
```

You can download latest wsk binary from here: https://github.com/apache/incubator-openwhisk-cli/releases/tag/latest

Originally was created because it was very useful to get back the .zip from packaged action.
Thanks to @dubeejw that implemented the feature.

**Comment by jthomas** [comment]
This is the best kind of feature request, one that already exists! 

I need to update my cli....

**Comment by csantanapr** [comment]
@jthomas if you are using IBM Functions the “bx wsk” already contains the feature.

**Comment by drcariel** [comment]
@csantanapr would it be useful to implement this for blackbox actions? or is that not feasible?

**Comment by csantanapr** [comment]
@drcariel   It already works for docker actions to extract a zip or source file from a docker action. 

I think providing something to extract the file system of the image into a tgz is impractical because of the many caveats
