### ISSUE TITLE
Eliminate need for second CLI build during Travis build

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk-cli#188]
Currently, a successful Travis invocation ends up building the Go CLI twice - once during the travis script, ./tools/travis/test_openwhisk.sh
```make build```
and a second time in the travis build_deploy stanza
```./tools/travis/build_tag_releases.sh $build_file_name $zip_file_name```

**Comment by dubeejw** [comment]
@jonpspri, FYI.

**Comment by jonpspri** [comment]
Yep.  I'm heading that way over in PR #184.  Still digging into how to move the build forward effectively in the process, especially because 'go' is not pretty when it comes to incremental builds.

Regards,
-J
