### ISSUE TITLE
Investigate why Travis is pulling from master incubator-openwhisk-client-go during build

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-cli#200]
Travis is failing as it is picking up changes from incubator-openwhisk-client-go and the companion has not been merged in this repo yet. The Travis build should run against the pinned version of client-go from the Godeps instead of master.

Build log: https://api.travis-ci.org/v3/job/330994467/log.txt

Added the error here:
```
commands/api.go:106: cannot range over api.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
commands/api.go:211: cannot range over retApi.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
commands/api.go:580: cannot range over resultApi.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
commands/api.go:618: cannot range over resultApi.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
commands/api.go:681: cannot range over resultApi.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
commands/api.go:715: cannot range over resultApi.Swagger.Paths[path] (type *whisk.ApiSwaggerPath)
```

Fail to build with the 'go build' command.

**Comment by dubeejw** [comment]
build_tag_releases.sh may not be running `go get`.

**Comment by houshengbo** [comment]
@dubeejw  I suspect the failure is not due to the wrong version of client go. The cli should be able to pin to the specified version of client go(not master), since almost day 1 these repo are separate. 

I can work on this issue.

**Comment by houshengbo** [comment]
@dubeejw The build failed because cli has new code, but does not pin to the latest version of client go.
The last commit of client go made the change to swagger: a086445: https://github.com/apache/incubator-openwhisk-client-go/commit/a0864455f7c18db70d93d4dd2bc0b43d2334ed90

**Comment by houshengbo** [comment]
The reason for that the PR passed before, but it failed on master: https://api.travis-ci.org/v3/job/330994467/log.txt, is probable a rebase issue.
when it is still pr, cli has not changed yet. when it is merged, there are several commits merged before this one. @dubeejw
