### ISSUE TITLE
Is there is reverse populate command opposite to ./gradlew goVendor

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-cli#212]
After running ./gradlew goVendor, we able to build binaries with native go command. However, we tried to run ./gradlew goTest, it did not run any tests. Do we need to un-populate vendors? Do we have a command to reverse ./gradlew goVendor? @jonpspri 
```
./gradlew goTest 

> Configure project :
Found go 1.8 in /usr/local/go/bin/go, use it.

> Task :goPrepare
Found global GOPATH: /Users/vincent/go.
```

**Comment by jonpspri** [comment]
Hmm... I need to do a little digging here...  Let me see if I can reproduce the behavior.
