### ISSUE TITLE
A list of source files missing Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-cli#222]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to below files.
```
Unapproved licenses:

  openwhisk-cli/tools/travis/test_openwhisk.sh
  openwhisk-cli/tests/dat/apigw/testswaggerdocinvalid
  openwhisk-cli/tests/dat/apigw/testswaggerdoc2
  openwhisk-cli/tests/dat/apigw/local.api.bad.yaml
  openwhisk-cli/tests/dat/apigw/local.api.yaml
  openwhisk-cli/tests/dat/apigw/testswaggerdoc1V2
  openwhisk-cli/tests/dat/apigw/testswaggerdoc1
  openwhisk-cli/tests/dat/apigw/testswaggerdoc2V2
  openwhisk-cli/tests/dat/actions/argCheck.js
  openwhisk-cli/tests/dat/actions/empty.js
  openwhisk-cli/tests/dat/actions/sort.js
  openwhisk-cli/tests/dat/actions/cat.js
  openwhisk-cli/tests/dat/actions/malformed.py
  openwhisk-cli/tests/dat/actions/echo-web-http.js
  openwhisk-cli/tests/dat/actions/initforever.js
  openwhisk-cli/tests/dat/actions/corsHeaderMod.js
  openwhisk-cli/tests/dat/actions/issue-1562.js
  openwhisk-cli/tests/dat/actions/timeout.js
  openwhisk-cli/tests/dat/actions/niam.py
  openwhisk-cli/tests/dat/actions/multipleHeaders.js
  openwhisk-cli/tests/dat/actions/helloAsync.js
  openwhisk-cli/tests/dat/actions/wc.js
  openwhisk-cli/tests/dat/actions/hello.swift
  openwhisk-cli/tests/dat/actions/malformed.js
  openwhisk-cli/tests/dat/actions/initexit.js
  openwhisk-cli/tests/dat/actions/hello.js
  openwhisk-cli/tests/dat/actions/helloContext.js
  openwhisk-cli/tests/dat/actions/helloDeadline.js
  openwhisk-cli/tests/dat/actions/log.js
  openwhisk-cli/tests/dat/actions/niam.js
  openwhisk-cli/tests/dat/actions/niam.swift
  openwhisk-cli/tests/dat/actions/wcbin.js
  openwhisk-cli/tests/dat/actions/helloOpenwhiskPackage.js
  openwhisk-cli/tests/dat/actions/textBody.js
  openwhisk-cli/tests/dat/actions/pngWeb.js
  openwhisk-cli/tests/dat/actions/base64Web.js
  openwhisk-cli/tests/dat/actions/countdown.js
  openwhisk-cli/tests/dat/actions/ping.js
  openwhisk-cli/tests/dat/actions/emptyJSONResult.js
  openwhisk-cli/tests/dat/actions/echo.js
  openwhisk-cli/tests/dat/actions/split.js
  openwhisk-cli/tests/dat/actions/asyncError.js
  openwhisk-cli/tests/dat/actions/helloPromise.js
  openwhisk-cli/tests/dat/actions/stdenv.py
  openwhisk-cli/tests/dat/actions/applicationError.js
  openwhisk-cli/tests/dat/actions/head.js
  openwhisk-cli/tests/dat/actions/printParams.js
  openwhisk-cli/tests/dat/actions/runexit.js
  openwhisk-cli/tests/src/dat/empty.js
  openwhisk-cli/tests/src/dat/malformed.js
  openwhisk-cli/tests/src/dat/hello.js
  openwhisk-cli/CONTRIBUTING.md
  openwhisk-cli/gradle.properties
  openwhisk-cli/notes.md
  openwhisk-cli/NOTICE.md
```
The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by mrutkows** [comment]
@daisy-ycguo today we exclude the test directories.  Likely we can document this exception at a minimum, but should try to add the "mini" approved ASF headers.

**Comment by daisy-ycguo** [comment]
It can be closed by PR #283 and #235

**Comment by mrutkows** [comment]
@daisy-ycguo The files under these "tests" may need headers as they are not performance related.

**Comment by daisy-ycguo** [comment]
@mrutkows These dat files under tests are removed. They are not there. So we can close this issue.

**Comment by dubee** [comment]
@daisy-ycguo, @mrutkows, can this issue be closed?

**Comment by mrutkows** [comment]
@dubee @daisy-ycguo I believe we noted this week that all the test files listed above were moved out of this repo. since the authoring of this issue.  IMO, we can close this issue and we should verify that these files now have licenses under where they appear to live now under incubator-openwhisk/tests directory.   Cursory examination of a few of these files indicates they now have headers.   

Regardless, this one can be closed IMO.

**Comment by mrutkows** [comment]
@daisy-ycguo @dubee for clarity, 

- tests/dat/actions/* 
- tests/dat/apigw/*

have all been moved to the main openwhisk repo. under the corresponding "tests" directory there: 
- https://github.com/apache/incubator-openwhisk/tree/master/tests/dat

and the remaining tests files under this repo. now all have ASF "mini" headers, that is:
-  openwhisk-cli/tests/src/dat/empty.js
-  openwhisk-cli/tests/src/dat/malformed.js
-  openwhisk-cli/tests/src/dat/hello.js
