### ISSUE TITLE
Output URL when creating/updating actions with --web true

### ISSUE THREAD

**Issue by glynnbird** [apache/incubator-openwhisk-cli#236]
If I create or update an action from the command-line like so:

```sh
$ wsk action update x x.js --web true
```

It would be really helpful if the `wsk` tool showed my the URL where I can access the URL. 

e.g.

```sh
$ wsk action update x x.js --web true
ok: created action x
url: https://openwhisk.ng.bluemix.net/api/v1/web/glynn.bird%40uk.ibm.com_dev/default/x.json
```

Just a suggestions :)

**Comment by dubeejw** [comment]
@glynnbird, you can use `wsk action get x --url`.

**Comment by glynnbird** [comment]
oh thanks @dubeejw. super helpful

**Comment by csantanapr** [comment]
This reminded me that we desperately need a “-s” silent mode to avoid getting the extra line printed “ok: created action x”
