### ISSUE TITLE
API with back-to-back path parameters fails

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk-cli#237]
Creating an API with multiple back-to-back path parameters fails
```
>bx wsk api create /dumpurl /two/{segment1}/{segment2} get showPathSegs --response-type http
error: Unable to create API: API creation failure: The parameter 'segment2' defined in path '/two/{segment1}/{segment2}' does not match any of the parameters defined for the path in the swagger file.
```
Multiple paths separated by a non-parameter path segment work correctly
```
>bx wsk api create /dumpurl /two/{segment1}/and/{segment2} get showPathSegs --response-type http
ok: created API /dumpurl/two/{segment1}/and/{segment2} GET for action /_/showPathSegs
https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/XXXXXXXXXX/dumpurl/two/{segment1}/and/{segment2}
```
Fix is needed for the following
1. Support back-to-back path segments
2. Error message in the context of the failing command does not make sense... that is, no swagger file was specified in the command, yet the error message indicates that a swagger file is in error.

**Comment by csantanapr** [comment]
Who can work on this?
