### ISSUE TITLE
For Ease of Maintenance, Update and Decide Where these Tests Should Live

### ISSUE THREAD

**Issue by drcariel** [apache/incubator-openwhisk-cli#259]
There is currently a level of manual syncing going on between duplicate test files that exist in both `https://github.com/apache/incubator-openwhisk-cli` and `https://github.com/apache/incubator-openwhisk`. I noticed the following files, sharing the same name unless indicated otherwise, that could use further investigation and/or updating:

- [x] `ApiGwEndToEndTests.scala`
- [x] `WskActionTests.scala`
- [x] `WskBasicJavaTests.scala`
- [x] `WskBasicNodeTests.scala` (Moved CLI versions from open to cli)
- [x] `WskBasicPythonTests.scala`
- [x] `WskBasicSwift3Tests.scala`
- [x] `WskCliBasicNodeTests.scala` (`WskCliBasicNodeDefaultTests.scala` and extended in other files to use both node 6  and 8)
- [x] `WskConsoleTests.scala`
- [x] `WskPackageTests.scala`
- [x] `WskRuleTests.scala` (diverged by 10 lines)
- [x] `WskSequenceTests.scala`
- [x] `ApiGwRoutemgmtActionTests.scala`
- [x] `BaseApiGwTests.scala`
- [x] `JsonArgsForTests.scala` (changed to depend on `TestJsonArgs.scala` in open)
- [x] `WskActionSequenceTests.scala`
- [x] `WskEntitlementTests.scala`
- [x] `WskWebActionsTests.scala` (diverged by 6 lines)
- [ ] ~`ApiGwTests.scala`~ (renamed to indicate rest vs cli in respective repos)
- [ ] ~`WskBasicUsageTests.scala`~ (renamed to indicate rest vs cli in respective repos)
- [ ] ~`WskBasicTests.scala`~ (renamed to indicate rest vs cli in respective repos)

Updating the test builds to rely on the original copies of most of the above that exist in `incubator-openwhisk` will be much easier to maintain. Which tests belong in this repo and vice versa?

**Comment by drcariel** [comment]
It seems to me that they are intended to be identical, however some seem to have diverged, as mentioned in my list above. There may be more divergences as I have only glanced at all the tests that seem identical at first.

**Comment by drcariel** [comment]
I will be working to remove the baseWsk versions from open-cli since we have the sources provided via openwhisk maven jar deps

**Comment by drcariel** [comment]
See the above PRs ☝️ , I have done my best to get the "low hanging fruit" of the lot. The 3 remaining; `WskBasicTests.scala`, `ApiGwTests.scala`, and `WskBasicUsageTests.scala` need some more work to get done right. ApiGw needs to be merged as it has diverged quite a bit and both of the others need to be centralized to use baseWsk then extended.

**Comment by mdeuser** [comment]
@drcariel - when a file in the description has been striked through, what does that mean? .. that the file will now be picked up from the incubator-openwhisk repo and deleted from the incubator-openwhisk-cli repo?

**Comment by mdeuser** [comment]
ah.. ok.  you might want to use the markdown checkboxes to track that kind of work instead of ~strikethroughs~
- [ ] put an 'x' in here when done :-)

**Comment by drcariel** [comment]
Closed via #3531
