### ISSUE TITLE
[Feature Request] Namespace option is required for standalone command execution

### ISSUE THREAD

**Issue by KeonHee** [apache/incubator-openwhisk-cli#296]
We are deploying shared packages to users with a CLI.

However, deployment sometimes fails because of the property already set up on the server.

It would be more convenient if we could set namespace and authentication independently whenever we run a command.

## Failure Case

1. Property already set
 - Namespace : `abc`
 - Auth: ${ABC_AUTH}

2. Update action on `def` namespace
```bash
wsk action update test --auth ${DEF_AUTH} # fail
```

## Example after modification
1. Property already set
 - Namespace : `abc`
 - Auth: ${ABC_AUTH}

2. Update action on `def` namespace
```bash
wsk action update test --auth ${DEF_AUTH} --namespace def # success!!
```

**Comment by rabbah** [comment]
Replace test with /namespace/test

**Comment by KeonHee** [comment]
OMG! Its working well. 
Thanks so much, I solved the problem.
