### ISSUE TITLE
is there no way to get action "code" except with --save

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-cli#325]
wsk action get omits the "code" by default. There is no way it appears to get the attached code except with `--save` which doesn't work for native actions (eg docker) even if they have a readable text or binary file.

@dubee can you confirm this is the case?

**Comment by dubee** [comment]
@rabbah, this is correct.

**Comment by rabbah** [comment]
Thanks. We should make it possible to download any attached exec even for blackbox then. Leaving marked as bug.

**Comment by rabbah** [comment]
@dubee I think you fixed this already - can you close if you agree?

**Comment by dubee** [comment]
Closing as fixed.
