### ISSUE TITLE
Batch mode in CLI

### ISSUE THREAD

**Issue by jeeteshchel** [apache/incubator-openwhisk-cli#345]
Hello, Currently API returns part of response as plain english text and remaining in json. For example below. Can a general batch mode be added to commands so that tools using the CLI can expect valid JSON response.
![image](https://user-images.githubusercontent.com/1531148/41664908-6c85d818-74af-11e8-961b-a050764e8203.png)

**Comment by rabbah** [comment]
+1 

We've discussed previously a `--raw` flag to strip any cli decoration but I cannot find the issue.

**Comment by csantanapr** [comment]
I like `--json` better, in case someone comes later asking for `--xml` or `--yaml` ala kubectl :-)

**Comment by rabbah** [comment]
closing as duplicate of https://github.com/apache/incubator-openwhisk-cli/issues/142.
