### ISSUE TITLE
unknown flag: --projectname for `wsk project export`

### ISSUE THREAD

**Issue by moritzraho** [apache/incubator-openwhisk-cli#412]
Using build from https://github.com/apache/incubator-openwhisk-cli/releases/download/latest/OpenWhisk_CLI-latest-mac-386.zip

```
> ./wsk project export --projectname myproject --manifest wskdeploy.yaml
unknown flag: --projectname
```

this works using the wskdeploy cli

**Comment by dubee** [comment]
@pritidesai, any idea on this one?

**Comment by pritidesai** [comment]
its missing that flag, just added, the PR is building.
