### ISSUE TITLE
Cannot list other spaces from CLI

### ISSUE THREAD

**Issue by thurt** [apache/incubator-openwhisk-cli#51]
I have multiple spaces under my organization name. I expected that I would be able to easily switch between spaces via the cli. However, running `wsk namespace list` will only show the namespace I am currently logged into. The issue is that I have to login to openwhisk via web browser to see my list of space names.

Is there a design reason why I cannot list all of the spaces from the CLI? Or is this a bug?

**Comment by rabbah** [comment]
A whisk key is associated with exactly one namespace. This is by design. If you're using OpenWhisk via Bluemix, you can use `wsk bluemix login` to switch namespaces (this automatically switched your key as well).

**Comment by thurt** [comment]
thanks for the info. i am able to switch namespaces with `wsk bluemix login`
