### ISSUE TITLE
Discuss Repo Organization

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-cli#6]
We need to discuss what the best plan is for setting up repos. Do we include go-whisk and go-whisk-cli in the same repo, or separate repos? @csantanapr, @mdeuser

**Comment by rabbah** [comment]
Historically they were two and I think that's the right approach. We should try to redirect the history from @theophoric as well (from blue) if possible - even if not the entire history, at least some of it. This was something we promised to look into when we resplit the repos.

**Comment by csantanapr** [comment]
I agree @rabbah we can even amend the commits to put his public github author info name/email

**Comment by houshengbo** [comment]
@dubeejw One example I can raise for the benefits of having separate repos for client-go and openwhisk-cli is the implementation of wskdeploy depends on openwhisk-client-go, but does not need to care about openwhisk-cli. We put openwhisk-client-go as a dependency for wskdeploy.

If the client-go(go-whisk) and openwhisk-cli(go-whisk-cli) are in the same repo, it has to download the openwhisk-cli as well each time wskdeploy pulls the dependencies, though cli is useless.

**Comment by houshengbo** [comment]
Let's close this issue so far, since we have already agreed to have two separate repos for cli and go-client. Feel free to reopen it, if you are still concerned about the structure.

**Comment by rabbah** [comment]
The structure is fine but we need to resolve the history preservation before long.

**Comment by rabbah** [comment]
Here are two links to the sdk and cli client with merged histories.
Feel free to clone them and push them to their respective repos under openwhisk.

https://github.com/rabbah/mergedcli
https://github.com/rabbah/mergedcli-client

i split openwhisk/tooks/cli right off of openwhisk master 608c7954437f133a7efc3e0ba8803eec33834891.

**Comment by rabbah** [comment]
If instead of splitting openwhisk master you want to merge the history with this repo's history, you can modify the steps below accordingly:

    git clone git@github.ibm.com:BlueMix-Fabric/go-whisk-cli.git
    git clone https://github.com/openwhisk/openwhisk.git
    mv openwhisk openwhisk-go-whisk-cli/
    cd openwhisk-go-whisk-cli/
    git filter-branch --prune-empty --subdirectory-filter tools/cli/go-whisk-cli master
    cd ../go-whisk-cli/
    git remote add new ../openwhisk-go-whisk-cli/
    git fetch new
    git merge  new/master
    # resolve conflicts (git status to see what needs resolution)
    git commit -m"Merging both histories." -a

You know the rest.

** You will likely have some conflicts to resolve. My resolution policy was brute force: copy all the files from the openwhisk repo as these are the golden sources now.

**Comment by houshengbo** [comment]
@rabbah @dubeejw 
Here is what I am going to do:
There are commits histories from three repos for either openwhisk-cli: git@github.ibm.com:BlueMix-Fabric/go-whisk-cli.git(old commits), https://github.com/openwhisk/openwhisk.git(recent CLI changes) and the current openwhisk-cli(recent separation commits).

I need to merge all the commits from them regarding the CLI in order to make the current openwhisk-cli repo both historically preservable and up-to-date.

The same step applies to openwhisk-client-go repo as well.

**Comment by houshengbo** [comment]
Both of openwhisk-client-go and openwhisk-cli repos preserve the historic commits now:
https://github.com/openwhisk/openwhisk-cli/master 
https://github.com/openwhisk/openwhisk-client-go/master

**Comment by csantanapr** [comment]
@houshengbo I don't think it preserved all the history, only the history from Nov 2016 when @paulcastro did a copy of the source code. I think the initial commits with the copy needs to be replace by the true commits that are before Nov 2016.

@dubeejw Can you double check what I saw ?

**Comment by houshengbo** [comment]
@csantanapr @dubeejw The initial commit has been retrogressed to on Jan 11, 2016 for openwhisk-cli and on Jan 19, 2016 for openwhisk-client-go.
I just re-did all the steps this morning.

**Comment by csantanapr** [comment]
@houshengbo sorry about it looks everything it's therein the history, I didn't page to the next level https://github.com/openwhisk/openwhisk-client-go/commits/master?after=5c216065673c15e35e0baa8feca9b986a6b73517+34
