### ISSUE TITLE
Add support for autocompletion, as with kubectl

### ISSUE THREAD

**Issue by krook** [apache/incubator-openwhisk-cli#91]
Other tools based on the same Cobra CLI framework have autocompletion support. This might make `wsk` CLI more user friendly.

https://github.com/spf13/cobra/pull/69
https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

**Comment by rabbah** [comment]
`wsk sdk install bashauto` for bash tab completion.

**Comment by krook** [comment]
Cool. Looks like I can close this one. Is there another issue open to improve the docs for `bashauto`?

**Comment by rabbah** [comment]
There isn't.
